from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from typing import Optional, List

app = FastAPI(
    title="Aurum Parfum API",
    description="Full Fragrance Catalog API for Aurum Parfum (Eau De Parfum 60ml)",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

perfumes = [
    # ==================== FOR MEN (M01 - M52) ====================
    {"id": "M01", "name": "212 Men", "code": "M01", "gender": "Men", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Fresh green citrus with gardenia, ginger, and sensual woody musk.",
     "top_notes": ["Spices", "Petitgrain", "Lavender", "Green Notes", "Grapefruit", "Bergamot"],
     "heart_notes": ["Ginger", "Gardenia", "Violet", "Sage"],
     "base_notes": ["Labdanum", "Sandalwood", "Musk", "Guaiac Wood", "Vetiver", "Incense"],
     "scent_profile": {"Fresh": 90, "Woody": 70, "Citrus": 80, "Warm": 40}, "best_season": "Spring / Summer", "best_occasion": "Daily Wear & Office", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "M02", "name": "Acqua Di Gio", "code": "M02", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Iconic aquatic breeze infused with sparkling citrus, rosemary, and cedarwood.",
     "top_notes": ["Lime", "Lemon", "Bergamot", "Jasmine", "Orange", "Mandarin"],
     "heart_notes": ["Sea Notes", "Jasmine", "Calone", "Peach", "Freesia", "Rosemary"],
     "base_notes": ["White Musk", "Cedar", "Oakmoss", "Patchouli", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 90, "Woody": 50, "Warm": 30}, "best_season": "Spring / Summer", "best_occasion": "Everyday Casual & Beach", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M03", "name": "Aventus Creed", "code": "M03", "gender": "Men", "category": "Woody", "tag": "Popular", "price": 250,
     "short_desc": "Smoky birch, crisp blackcurrant, juicy pineapple, and rich oakmoss.",
     "top_notes": ["Bergamot", "Blackcurrant", "Apple", "Pineapple"],
     "heart_notes": ["Juniper Berries", "Birch", "Patchouli", "Jasmine"],
     "base_notes": ["Musk", "Oakmoss", "Ambergris", "Vanilla"],
     "scent_profile": {"Woody": 90, "Fresh": 75, "Warm": 70, "Sweet": 40}, "best_season": "All Seasons", "best_occasion": "Executive, Formal & Signature", "longevity": "10–12 hours", "projection": "Strong"},
    {"id": "M04", "name": "Axe Dark Temptation", "code": "M04", "gender": "Men", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Irresistible hot chocolate and amber blend accented by red peppercorn.",
     "top_notes": ["Pear", "Ginger", "Coriander", "Cherry"],
     "heart_notes": ["Red Pepper", "Basil", "Sage"],
     "base_notes": ["Dark Chocolate", "Vanilla", "Whipped Cream", "Amber", "Patchouli"],
     "scent_profile": {"Sweet": 95, "Warm": 85, "Woody": 40, "Fresh": 20}, "best_season": "Autumn / Winter", "best_occasion": "Casual & Evening", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M05", "name": "Baccarat Rouge 540", "code": "M05", "gender": "Unisex", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Luminous amber, blood orange, and saffron with airy cedarwood sophistication.",
     "top_notes": ["Saffron", "Jasmine"],
     "heart_notes": ["Amberwood", "Ambergris"],
     "base_notes": ["Fir Resin", "Cedar"],
     "scent_profile": {"Woody": 90, "Warm": 90, "Sweet": 80, "Fresh": 25}, "best_season": "All Seasons", "best_occasion": "Special Events & Gala Night", "longevity": "12+ hours", "projection": "Enormous"},
    {"id": "M06", "name": "Bad Boy (Carolina Herrera)", "code": "M06", "gender": "Men", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Bold contrast of white pepper, dark tonka bean, and cocoa.",
     "top_notes": ["White Pepper", "Black Pepper", "Bergamot"],
     "heart_notes": ["Sage", "Cedar"],
     "base_notes": ["Tonka Bean", "Cacao", "Amberwood"],
     "scent_profile": {"Sweet": 85, "Warm": 90, "Woody": 70, "Fresh": 30}, "best_season": "Autumn / Winter", "best_occasion": "Night Out & Party", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "M07", "name": "Benetton Cold", "code": "M07", "gender": "Men", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Crisp citrus burst paired with aromatic lavender, thyme, and patchouli.",
     "top_notes": ["Bergamot", "Aldehydes", "Mandarin"],
     "heart_notes": ["Lavender", "Coriander", "Red Pepper"],
     "base_notes": ["Patchouli", "Vetiver", "White Musk", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Woody": 40, "Warm": 20}, "best_season": "Summer / Daytime", "best_occasion": "Gym & Casual Day Out", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "M08", "name": "Black XS", "code": "M08", "gender": "Men", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Vibrant lemon and praline spiced with black cardamom and rosewood.",
     "top_notes": ["Citrus", "Lemon", "Tagetes", "Sage"],
     "heart_notes": ["Praline", "Cinnamon", "Tolu Balsam", "Black Cardamom"],
     "base_notes": ["Brazilian Rosewood", "Patchouli", "Black Amber"],
     "scent_profile": {"Sweet": 85, "Warm": 80, "Woody": 60, "Citrus": 40}, "best_season": "Autumn / Winter", "best_occasion": "Clubbing & Date Night", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "M09", "name": "Bleu De Chanel", "code": "M09", "gender": "Men", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Aromatic woody fragrance featuring crisp mint, pink pepper, and cedar.",
     "top_notes": ["Grapefruit", "Lemon", "Mint", "Pink Pepper"],
     "heart_notes": ["Ginger", "Nutmeg", "Jasmine", "Iso E Super"],
     "base_notes": ["Incense", "Vetiver", "Cedar", "Sandalwood", "Patchouli"],
     "scent_profile": {"Woody": 90, "Fresh": 85, "Citrus": 70, "Warm": 60}, "best_season": "All Seasons", "best_occasion": "Signature Daily & Business", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "M10", "name": "Bvlgari Extreme", "code": "M10", "gender": "Men", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Intense Darjeeling tea note fused with vibrant bergamot and dry woods.",
     "top_notes": ["Tea", "Grapefruit", "Bergamot", "Neroli", "Petitgrain"],
     "heart_notes": ["Balsam Fir", "Guaiac Wood", "Pepper", "Nutmeg", "Rosewood"],
     "base_notes": ["Musk", "Cedar", "Oakmoss", "Sandalwood"],
     "scent_profile": {"Woody": 85, "Fresh": 80, "Citrus": 70, "Warm": 40}, "best_season": "Spring / Summer", "best_occasion": "Office & Professional Meetings", "longevity": "8–10 hours", "projection": "Moderate to Strong"},
    {"id": "M11", "name": "Bvlgari Man in Black", "code": "M11", "gender": "Men", "category": "Woody", "tag": "Popular", "price": 250,
     "short_desc": "Sensual spiced rum, leather accord, and powdery iris over guaiac wood.",
     "top_notes": ["Spices", "Rum", "Tobacco"],
     "heart_notes": ["Leather", "Iris", "Tuberose"],
     "base_notes": ["Tonka Bean", "Guaiac Wood", "Benzoin"],
     "scent_profile": {"Warm": 95, "Woody": 85, "Sweet": 60, "Fresh": 15}, "best_season": "Autumn / Winter", "best_occasion": "Formal Evening & Cold Weather", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "M12", "name": "Burberry Weekend Men", "code": "M12", "gender": "Men", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Relaxing citrus cocktail of lemon, grapefruit, ivy leaves, and sandalwood.",
     "top_notes": ["Lemon", "Grapefruit", "Bergamot", "Pineapple", "Melon", "Mandarin"],
     "heart_notes": ["Ivy", "Oakmoss", "Sandalwood"],
     "base_notes": ["Honey", "Musk", "Amber"],
     "scent_profile": {"Citrus": 90, "Fresh": 85, "Sweet": 40, "Woody": 40}, "best_season": "Spring / Summer", "best_occasion": "Weekend Leisure & Relaxation", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M13", "name": "Bvlgari AquaMarine", "code": "M13", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Crisp aquatic vitality driven by Posidonia sea algae, neroli, and cedar.",
     "top_notes": ["Grapefruit", "Neroli", "Mandarin", "Petitgrain"],
     "heart_notes": ["Water Notes", "Seaweed", "Rosemary"],
     "base_notes": ["Virginia Cedar", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 75, "Woody": 45, "Warm": 20}, "best_season": "Summer Days", "best_occasion": "Beach Trips & Sunny Outings", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M14", "name": "CK Be", "code": "M14", "gender": "Unisex", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Intimate floral-woody musk with juniper berry, mint, and white peach.",
     "top_notes": ["Lavender", "Green Notes", "Mint", "Mandarin", "Juniper", "Bergamot"],
     "heart_notes": ["Green Grass", "Magnolia", "Orchid", "Freesia", "Peach", "Jasmine"],
     "base_notes": ["Sandalwood", "Amber", "Opoponax", "Musk", "Cedar", "Vanilla"],
     "scent_profile": {"Fresh": 85, "Woody": 60, "Floral": 50, "Warm": 40}, "best_season": "Spring / Summer", "best_occasion": "Casual Everyday & Lounging", "longevity": "5–7 hours", "projection": "Intimate"},
    {"id": "M15", "name": "CK Eternity", "code": "M15", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Timeless fougère blending cool lavender, geranium, sage, and vetiver.",
     "top_notes": ["Lavender", "Lemon", "Bergamot", "Mandarin"],
     "heart_notes": ["Sage", "Juniper Berries", "Basil", "Geranium", "Jasmine", "Orange Blossom"],
     "base_notes": ["Sandalwood", "Vetiver", "Musk", "Rosewood", "Amber"],
     "scent_profile": {"Fresh": 90, "Woody": 65, "Floral": 40, "Warm": 45}, "best_season": "Spring / Summer / Autumn", "best_occasion": "Daily Work & Formal Events", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M16", "name": "CK One", "code": "M16", "gender": "Unisex", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Clean, youthful harmony of pineapple, green tea, papaya, and amber.",
     "top_notes": ["Lemon", "Green Notes", "Bergamot", "Pineapple", "Mandarin", "Cardamom", "Papaya"],
     "heart_notes": ["Lily-of-the-Valley", "Jasmine", "Violet", "Nutmeg", "Rose", "Orris Root"],
     "base_notes": ["Green Accord", "Musk", "Cedar", "Sandalwood", "Oakmoss", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Floral": 40, "Woody": 30}, "best_season": "Summer / Spring", "best_occasion": "Casual Wear & School/Gym", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M17", "name": "Clinique Happy Men", "code": "M17", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Sunny uplifting burst of juicy lime, mandarin, sea spray, and cedar.",
     "top_notes": ["Lime", "Green Notes", "Mandarin", "Lemon", "Sea Notes"],
     "heart_notes": ["Freesia", "Jasmine", "Lily-of-the-Valley", "Rose"],
     "base_notes": ["Cypress", "Cedar", "Musk", "Guaiac Wood"],
     "scent_profile": {"Citrus": 95, "Fresh": 90, "Woody": 40, "Floral": 30}, "best_season": "Spring / Summer", "best_occasion": "Daytime & Mood Booster", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "M18", "name": "Cool Water Men", "code": "M18", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "The quintessential oceanic splash of mint, seawater, lavender, and tobacco.",
     "top_notes": ["Sea Water", "Mint", "Green Notes", "Lavender", "Coriander", "Rosemary"],
     "heart_notes": ["Sandalwood", "Jasmine", "Neroli", "Geranium"],
     "base_notes": ["Musk", "Oakmoss", "Cedar", "Tobacco", "Amber"],
     "scent_profile": {"Fresh": 95, "Woody": 50, "Warm": 35, "Citrus": 30}, "best_season": "Spring / Summer", "best_occasion": "Daily Work, Sports & Outdoor", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M19", "name": "D&G Light Blue Men", "code": "M19", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Sun-drenched Mediterranean grapefruit, juniper, Sichuan pepper, and oakmoss.",
     "top_notes": ["Grapefruit", "Bergamot", "Sicilian Mandarin", "Juniper"],
     "heart_notes": ["Pepper", "Rosemary", "Brazilian Rosewood"],
     "base_notes": ["Musk", "Incense", "Oakmoss"],
     "scent_profile": {"Citrus": 90, "Fresh": 90, "Woody": 60, "Warm": 35}, "best_season": "Summer Days", "best_occasion": "Vacations & Outdoor Dates", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "M20", "name": "Drakkar Noir", "code": "M20", "gender": "Men", "category": "Woody", "tag": "Classic", "price": 250,
     "short_desc": "Powerful vintage fougère loaded with dark lavender, spicy coriander, and leather.",
     "top_notes": ["Lavender", "Lemon", "Bergamot", "Mint", "Rosemary", "Lemon Verbena", "Basil"],
     "heart_notes": ["Juniper", "Coriander", "Cinnamon", "Carnation", "Wormwood", "Angelica"],
     "base_notes": ["Oakmoss", "Leather", "Fir", "Pine Tree Needles", "Sandalwood", "Vetiver", "Patchouli", "Cedar"],
     "scent_profile": {"Woody": 95, "Fresh": 70, "Warm": 75, "Sweet": 20}, "best_season": "Autumn / Winter", "best_occasion": "Evening & Confident Formal", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "M21", "name": "Dunhill Desire Blue", "code": "M21", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Deep aquatic blend of litchi, lotus leaf, orange, and sea breeze.",
     "top_notes": ["Litchi", "Mandarin Orange", "Lotus", "Bergamot"],
     "heart_notes": ["Sea Notes", "Orange", "Brazilian Rosewood"],
     "base_notes": ["Tonka Bean", "Amber", "Musk", "Benzoin"],
     "scent_profile": {"Fresh": 90, "Sweet": 65, "Citrus": 60, "Warm": 40}, "best_season": "Spring / Summer", "best_occasion": "Casual Day & Hanging Out", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M22", "name": "Fahrenheit", "code": "M22", "gender": "Men", "category": "Woody", "tag": "Classic", "price": 250,
     "short_desc": "Legendary gasoline-violet accord wrapped in rich leather and nutmeg.",
     "top_notes": ["Nutmeg Flower", "Lavender", "Cedar", "Chamomile", "Mandarin", "Hawthorn", "Bergamot", "Lemon"],
     "heart_notes": ["Violet Leaf", "Nutmeg", "Cedar", "Sandalwood", "Carnation", "Honeysuckle", "Jasmine", "Lily-of-the-Valley"],
     "base_notes": ["Leather", "Vetiver", "Musk", "Amber", "Patchouli", "Tonka Bean"],
     "scent_profile": {"Woody": 90, "Warm": 85, "Floral": 50, "Fresh": 40}, "best_season": "Autumn / Winter", "best_occasion": "Biker & Bold Evening", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "M23", "name": "Ferrari Black", "code": "M23", "gender": "Men", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Red apple, plum, cinnamon, and warm vanilla musk for easy elegance.",
     "top_notes": ["Red Apple", "Plum", "Lime", "Bergamot"],
     "heart_notes": ["Cinnamon", "Jasmine", "Cardamom", "Rose"],
     "base_notes": ["Vanilla", "Amber", "Musk", "Cedar"],
     "scent_profile": {"Sweet": 85, "Warm": 75, "Citrus": 60, "Woody": 50}, "best_season": "Autumn / Spring", "best_occasion": "Casual Evenings & Dates", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "M24", "name": "Gucci Guilty", "code": "M24", "gender": "Men", "category": "Woody", "tag": "Popular", "price": 250,
     "short_desc": "Sensual Italian lemon, orange blossom, and charismatic cedarwood.",
     "top_notes": ["Lavender", "Amalfi Lemon"],
     "heart_notes": ["African Orange Flower"],
     "base_notes": ["Virginia Cedar", "Patchouli", "Vanilla"],
     "scent_profile": {"Woody": 80, "Citrus": 75, "Floral": 60, "Warm": 50}, "best_season": "All Seasons", "best_occasion": "Night Out & Romantic Dinners", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M25", "name": "Guess Man", "code": "M25", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Effortless Italian bergamot, green apple, ginger, and blue lavender.",
     "top_notes": ["Wormwood"],
     "heart_notes": ["Nutmeg", "White Pepper", "Ginger", "Lavender"],
     "base_notes": ["Sandalwood", "Peru Balsam", "Fir", "Amber", "Musk", "Suede"],
     "scent_profile": {"Fresh": 80, "Woody": 70, "Warm": 60, "Citrus": 40}, "best_season": "Spring / Autumn", "best_occasion": "Everyday Office & Casual", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M26", "name": "Hugo Boss (Bottled)", "code": "M26", "gender": "Men", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Warm spiced apple pie with cinnamon, clove, and rich sandalwood.",
     "top_notes": ["Apple", "Plum", "Lemon", "Bergamot", "Oakmoss", "Geranium"],
     "heart_notes": ["Cinnamon", "Mahogany", "Carnation"],
     "base_notes": ["Vanilla", "Sandalwood", "Cedar", "Vetiver", "Olive Tree"],
     "scent_profile": {"Warm": 90, "Sweet": 80, "Woody": 75, "Citrus": 40}, "best_season": "Autumn / Winter", "best_occasion": "Professional Suit & Everyday", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M27", "name": "Hugo Boss Dark Blue", "code": "M27", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Spicy gin-tonic citrus blend with suede, sage, and mahogany wood.",
     "top_notes": ["Ginger", "Grapefruit", "Orange", "Lemon", "Lime"],
     "heart_notes": ["Cypress", "Geranium", "Cardamom", "Mahogany", "Sage"],
     "base_notes": ["Vanilla", "Cedar", "Vetiver", "Benzoin", "Patchouli"],
     "scent_profile": {"Fresh": 80, "Warm": 70, "Citrus": 70, "Woody": 60}, "best_season": "Spring / Autumn", "best_occasion": "Evening Gathering & Lounge", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M28", "name": "Hugo Boss Energised", "code": "M28", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Electrifying burst of bitter citrus, cool mint, and vibrant pink pepper.",
     "top_notes": ["Mint", "Pink Pepper", "Citrus Notes", "Kumquat", "Pineapple"],
     "heart_notes": ["Cardamom", "Jasmine", "Nutmeg", "Juniper"],
     "base_notes": ["Leather", "Teak Wood", "Vanilla"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Woody": 45, "Warm": 30}, "best_season": "Spring / Summer", "best_occasion": "Workouts, Sports & Active Day", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M29", "name": "Invictus (Paco Rabanne)", "code": "M29", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Champion's trophy of marine accord, laurel leaf, grapefruit, and ambergris.",
     "top_notes": ["Sea Notes", "Grapefruit", "Mandarin Orange"],
     "heart_notes": ["Bay Leaf", "Jasmine"],
     "base_notes": ["Ambergris", "Guaiac Wood", "Oakmoss", "Patchouli"],
     "scent_profile": {"Fresh": 90, "Sweet": 70, "Citrus": 70, "Woody": 50}, "best_season": "All Seasons", "best_occasion": "Gym, Active Casual & Dates", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "M30", "name": "Issey Miyake L'Eau d'Issey", "code": "M30", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Zen waterfall of Japanese Yuzu citrus, lotus, nutmeg, and blue cedar.",
     "top_notes": ["Yuzu", "Lemon", "Bergamot", "Lemon Verbena", "Mandarin", "Cypress", "Coriander", "Tarragon"],
     "heart_notes": ["Blue Lotus", "Nutmeg", "Lily-of-the-Valley", "Saffron", "Bourbon Geranium", "Cinnamon"],
     "base_notes": ["Tahitian Vetiver", "Musk", "Cedar", "Sandalwood", "Tobacco", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 90, "Woody": 60, "Warm": 30}, "best_season": "Spring / Summer", "best_occasion": "Hot Days & Fresh Office Scent", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M31", "name": "James Bond 007", "code": "M31", "gender": "Men", "category": "Woody", "tag": "Popular", "price": 250,
     "short_desc": "Sophisticated British moss, crisp apple, lavender, and Haitian vetiver.",
     "top_notes": ["Apple", "Bergamot", "Geranium"],
     "heart_notes": ["Rose", "Lavender", "Cardamom"],
     "base_notes": ["Moss", "Sandalwood", "Vetiver", "Patchouli"],
     "scent_profile": {"Woody": 85, "Fresh": 70, "Warm": 65, "Sweet": 30}, "best_season": "Autumn / Winter", "best_occasion": "Evening & Formal Dinner", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "M32", "name": "Jovan White Musk Men", "code": "M32", "gender": "Men", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Clean comforting white musk, sweet citrus, melon, and blonde woods.",
     "top_notes": ["Melon", "Granny Smith Apple", "Citrus", "Mint"],
     "heart_notes": ["Thyme", "Carnation", "Geranium"],
     "base_notes": ["White Musk", "Woodsy Notes"],
     "scent_profile": {"Fresh": 85, "Warm": 60, "Woody": 45, "Floral": 30}, "best_season": "All Seasons", "best_occasion": "Bedtime & After Shower Freshness", "longevity": "5–7 hours", "projection": "Intimate to Moderate"},
    {"id": "M33", "name": "Lacoste Black", "code": "M33", "gender": "Men", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Refreshing watermelon and French lavender warming into dark chocolate cashmeran.",
     "top_notes": ["Watermelon"],
     "heart_notes": ["Basil", "Lavender", "Verbena"],
     "base_notes": ["Dark Chocolate", "Cashmeran", "Patchouli", "Coumarin"],
     "scent_profile": {"Woody": 80, "Sweet": 70, "Fresh": 65, "Warm": 60}, "best_season": "Spring / Summer Nights", "best_occasion": "Night Out & Casual Dating", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "M34", "name": "Lacoste Blue", "code": "M34", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Invigorating grapefruit, peppermint, watery notes, and crisp oakmoss.",
     "top_notes": ["Grapefruit", "Peppermint"],
     "heart_notes": ["Sage", "Orange Blossom"],
     "base_notes": ["Patchouli", "Cedar", "Fern"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Woody": 50, "Warm": 20}, "best_season": "Summer Days", "best_occasion": "Sports, Gym & Hot Weather", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M35", "name": "Lacoste Green", "code": "M35", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Natural blend of Italian bergamot, iced melon, verbena, and blue lavender.",
     "top_notes": ["Grapefruit", "Bergamot", "Melon", "Verbena"],
     "heart_notes": ["Lavender", "Thyme", "Fig", "Birch Leaf"],
     "base_notes": ["Bamboo Wood"],
     "scent_profile": {"Fresh": 90, "Citrus": 80, "Woody": 50, "Warm": 20}, "best_season": "Spring / Summer", "best_occasion": "Outdoor Walks & Casual Brunch", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "M36", "name": "Lacoste Red", "code": "M36", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "High-octane green apple, pine tree, jasmine, and precious white musk.",
     "top_notes": ["Green Apple"],
     "heart_notes": ["Pine Tree"],
     "base_notes": ["Patchouli", "Vetiver"],
     "scent_profile": {"Fresh": 85, "Woody": 75, "Citrus": 60, "Warm": 40}, "best_season": "Spring / Summer / Autumn", "best_occasion": "Active Days & Campus", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M37", "name": "Lacoste Style in Play", "code": "M37", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Green Maclura fruits, cedar leaves, jasmine, and woody patchouli.",
     "top_notes": ["Green Apple", "Thuja"],
     "heart_notes": ["Pine Tree", "Cedar", "Jasmine"],
     "base_notes": ["Patchouli", "White Musk", "Vetiver"],
     "scent_profile": {"Fresh": 85, "Woody": 75, "Warm": 45, "Citrus": 40}, "best_season": "Spring / Summer", "best_occasion": "Sports & Dynamic Activities", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M38", "name": "Lacoste White", "code": "M38", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Clean crisp white polo vibe with grapefruit, cardamom, tuberose, and suede.",
     "top_notes": ["Grapefruit", "Cardamom", "Rosemary"],
     "heart_notes": ["Tuberose", "Ylang-Ylang"],
     "base_notes": ["Cedar", "Leather", "Suede", "Vetiver"],
     "scent_profile": {"Fresh": 90, "Floral": 60, "Woody": 60, "Citrus": 60}, "best_season": "Spring / Summer", "best_occasion": "Crisp White Shirt Daily Wear", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "M39", "name": "Le Male (Jean Paul Gaultier)", "code": "M39", "gender": "Men", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Timeless barbershop lavender, mint, and warm seductive vanilla.",
     "top_notes": ["Lavender", "Mint", "Cardamom", "Bergamot", "Artemisia"],
     "heart_notes": ["Cinnamon", "Orange Blossom", "Caraway"],
     "base_notes": ["Vanilla", "Tonka Bean", "Amber", "Sandalwood", "Cedar"],
     "scent_profile": {"Sweet": 90, "Warm": 90, "Fresh": 70, "Woody": 50}, "best_season": "Autumn / Winter / Spring", "best_occasion": "Romantic Date & Night Out", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "M40", "name": "Montblanc Legend", "code": "M40", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Modern masculine lavender, pineapple, oakmoss accord, and tonka bean.",
     "top_notes": ["Lavender", "Pineapple", "Bergamot", "Lemon Verbena"],
     "heart_notes": ["Red Apple", "Dried Fruits", "Oakmoss", "Geranium", "Coumarin", "Rose"],
     "base_notes": ["Tonka Bean", "Sandalwood"],
     "scent_profile": {"Fresh": 85, "Woody": 70, "Sweet": 60, "Warm": 50}, "best_season": "All Seasons", "best_occasion": "Office, Versatile & Casual", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M41", "name": "Neroli Portofino Aqua", "code": "M41", "gender": "Unisex", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Sparkling Italian Riviera neroli, bitter orange, lemon, and white amber.",
     "top_notes": ["Lemon", "Bergamot", "Bitter Orange"],
     "heart_notes": ["Neroli", "Orange Blossom"],
     "base_notes": ["White Musk", "Amberwood"],
     "scent_profile": {"Fresh": 95, "Citrus": 95, "Floral": 60, "Warm": 20}, "best_season": "Summer / Hot Days", "best_occasion": "Vacation & Warm Weather", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "M42", "name": "One Million (Paco Rabanne)", "code": "M42", "gender": "Men", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Gold standard of blood mandarin, spicy cinnamon, rose, and amber leather.",
     "top_notes": ["Blood Mandarin", "Grapefruit", "Mint"],
     "heart_notes": ["Cinnamon", "Spicy Notes", "Rose"],
     "base_notes": ["Amber", "Leather", "Woody Notes", "Indian Patchouli"],
     "scent_profile": {"Sweet": 90, "Warm": 90, "Woody": 60, "Citrus": 40}, "best_season": "Autumn / Winter", "best_occasion": "Clubbing, Party & Night Life", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "M43", "name": "Polo Black", "code": "M43", "gender": "Men", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Iced mango, Spanish sage, silver armoise, and rich noir patchouli.",
     "top_notes": ["Iced Mango", "Sage", "Green Notes"],
     "heart_notes": ["Artemisia", "Hedione", "Tangerine"],
     "base_notes": ["Patchouli", "Sandalwood", "Tonka Bean"],
     "scent_profile": {"Woody": 80, "Fresh": 75, "Sweet": 65, "Warm": 50}, "best_season": "All Seasons", "best_occasion": "Evening Dates & Smart Casual", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M44", "name": "Polo Blue", "code": "M44", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Open sky blue air with crisp melon, cucumber, washed suede, and basil.",
     "top_notes": ["Cucumber", "Melon", "Mandarin Orange"],
     "heart_notes": ["Basil", "Sage", "Geranium"],
     "base_notes": ["Suede", "Woodsy Notes", "Musk"],
     "scent_profile": {"Fresh": 95, "Citrus": 70, "Woody": 50, "Warm": 30}, "best_season": "Spring / Summer", "best_occasion": "Casual & Sunny Office Wear", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M45", "name": "Polo Red", "code": "M45", "gender": "Men", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Fiery red grapefruit, deep red saffron, and roasted red coffee beans.",
     "top_notes": ["Cranberry", "Grapefruit", "Italian Lemon"],
     "heart_notes": ["Saffron", "Sage"],
     "base_notes": ["Amber", "Coffee", "Woodsy Notes"],
     "scent_profile": {"Sweet": 85, "Warm": 80, "Citrus": 70, "Woody": 50}, "best_season": "Autumn / Winter / Spring", "best_occasion": "Exciting Nights & Social Hangouts", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "M46", "name": "Polo Sport", "code": "M46", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Athletic powerhouse of mint, seaweed, mandarin, ginger, and sandalwood.",
     "top_notes": ["Mint", "Aldehydes", "Lavender", "Bergamot", "Mandarin", "Lemon", "Artemisia", "Neroli"],
     "heart_notes": ["Seagrass", "Ginger", "Jasmine", "Geranium", "Brazilian Rosewood", "Cyclamen", "Rose"],
     "base_notes": ["Musk", "Sandalwood", "Cedar", "Guaiac Wood", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 80, "Woody": 50, "Warm": 30}, "best_season": "Summer / Daytime", "best_occasion": "Gym, Sports & Outdoor Work", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M47", "name": "Sauvage (Dior)", "code": "M47", "gender": "Men", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Calabrian bergamot and fiery pepper over powerful ambroxan and cedar.",
     "top_notes": ["Calabrian Bergamot", "Pepper"],
     "heart_notes": ["Sichuan Pepper", "Lavender", "Pink Pepper", "Vetiver", "Patchouli", "Geranium", "Elemi"],
     "base_notes": ["Ambroxan", "Cedar", "Labdanum"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Woody": 70, "Warm": 50}, "best_season": "All Seasons", "best_occasion": "Signature Office, Dates & Clubbing", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "M48", "name": "Swiss Army", "code": "M48", "gender": "Men", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Crisp mountain air, mint, yuzu, edelweiss, and cedar needles.",
     "top_notes": ["Mint", "Green Notes", "Bergamot", "Yuzu", "Ginger"],
     "heart_notes": ["Lavender", "Rosemary", "Violet Leaf", "Edelweiss", "Geranium"],
     "base_notes": ["Cypress", "Cedar", "Balsam Fir", "Musk", "Amber"],
     "scent_profile": {"Fresh": 90, "Woody": 70, "Citrus": 60, "Warm": 30}, "best_season": "Spring / Autumn", "best_occasion": "Adventure, Hiking & Everyday", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M49", "name": "Tommy Boy", "code": "M49", "gender": "Men", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "All-American apple pie, spearmint, cranberry, and warm cotton accords.",
     "top_notes": ["Mint", "Bergamot", "Grapefruit", "Lavender"],
     "heart_notes": ["Granny Smith Apple", "Cranberry", "Rose"],
     "base_notes": ["Cotton Flower", "Cactus", "Amber"],
     "scent_profile": {"Fresh": 90, "Citrus": 75, "Sweet": 60, "Woody": 40}, "best_season": "Spring / Summer", "best_occasion": "Campus, Casual & Daylight Hangs", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "M50", "name": "Ultramale (Jean Paul Gaultier)", "code": "M50", "gender": "Men", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Irresistible gourmand blend of sweet pear, black lavender, cinnamon, and vanilla.",
     "top_notes": ["Pear", "Lavender", "Mint", "Bergamot", "Lemon"],
     "heart_notes": ["Cinnamon", "Clary Sage", "Caraway"],
     "base_notes": ["Black Vanilla Husk", "Amber", "Patchouli", "Cedar"],
     "scent_profile": {"Sweet": 95, "Warm": 90, "Woody": 60, "Fresh": 40}, "best_season": "Autumn / Winter", "best_occasion": "Clubbing, Evening Dates & Parties", "longevity": "10–12 hours", "projection": "Enormous"},
    {"id": "M51", "name": "Versace Dylan Blue", "code": "M51", "gender": "Men", "category": "Woody", "tag": "Popular", "price": 250,
     "short_desc": "Mediterranean bergamot, fig leaf, aquatic notes, violet, and dark incense.",
     "top_notes": ["Calabrian Bergamot", "Water Notes", "Grapefruit", "Fig Leaf"],
     "heart_notes": ["Ambroxan", "Black Pepper", "Patchouli", "Violet Leaf", "Papyrus"],
     "base_notes": ["Incense", "Musk", "Tonka Bean", "Saffron"],
     "scent_profile": {"Fresh": 85, "Woody": 80, "Warm": 70, "Citrus": 65}, "best_season": "All Seasons", "best_occasion": "Office, Night Out & Versatile", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "M52", "name": "Versace Eros", "code": "M52", "gender": "Men", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Passionate mint leaves, Italian lemon zest, green apple, and creamy vanilla.",
     "top_notes": ["Mint", "Green Apple", "Lemon"],
     "heart_notes": ["Tonka Bean", "Ambroxan", "Geranium"],
     "base_notes": ["Madagascar Vanilla", "Virginian Cedar", "Atlas Cedar", "Vetiver", "Oakmoss"],
     "scent_profile": {"Sweet": 90, "Fresh": 85, "Warm": 80, "Woody": 60}, "best_season": "All Seasons / Night", "best_occasion": "Parties, Dates & Nightlife", "longevity": "9–11 hours", "projection": "Strong"},

    # ==================== FOR WOMEN (W01 - W72) ====================
    {"id": "W01", "name": "Angel's Breath", "code": "W01", "gender": "Women", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Nostalgic, powdery baby cologne freshness with light floral whisper.",
     "top_notes": ["Citrus", "Lemon Verbena"], "heart_notes": ["Lavender", "Floral Notes"], "base_notes": ["Powdery Accord", "Musk"],
     "scent_profile": {"Fresh": 95, "Floral": 60, "Citrus": 50, "Sweet": 30}, "best_season": "All Seasons", "best_occasion": "Bedtime & Everyday Casual", "longevity": "5–7 hours", "projection": "Intimate"},
    {"id": "W02", "name": "Ariana Grande Ari", "code": "W02", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Luscious crispy pear, pink grapefruit, marshmallow, and creamy musk.",
     "top_notes": ["Raspberry", "Pear", "Grapefruit"], "heart_notes": ["Vanilla Orchid", "Lily-of-the-Valley", "Rose"], "base_notes": ["Marshmallow", "Musk", "Woodsy Notes"],
     "scent_profile": {"Sweet": 95, "Floral": 60, "Citrus": 40, "Warm": 40}, "best_season": "Spring / Autumn", "best_occasion": "Fun Outings & Dates", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W03", "name": "Ariana Grande Cloud", "code": "W03", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Airy whipped coconut cream, praline, lavender blossom, and vanilla orchid.",
     "top_notes": ["Lavender", "Pear", "Bergamot"], "heart_notes": ["Whipped Cream", "Praline", "Coconut", "Vanilla Orchid"], "base_notes": ["Musk", "Woody Notes"],
     "scent_profile": {"Sweet": 95, "Warm": 80, "Floral": 50, "Fresh": 30}, "best_season": "All Seasons", "best_occasion": "Cozy Days, Dating & Campus", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "W04", "name": "B&BW Cucumber Melon", "code": "W04", "gender": "Women", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Crisp green cucumber and sweet juicy cantaloupe melon refresher.",
     "top_notes": ["Melon", "Cucumber"], "heart_notes": ["Watery Notes", "Lily-of-the-Valley"], "base_notes": ["Musk"],
     "scent_profile": {"Fresh": 95, "Sweet": 70, "Floral": 30, "Woody": 10}, "best_season": "Summer Days", "best_occasion": "Casual & Everyday Fresh", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W05", "name": "B&BW Dark Kiss", "code": "W05", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Black raspberry, burgundy rose, dark vanilla bean, and plum incense.",
     "top_notes": ["Blackberry", "Plum", "Incense", "Mirabelle"], "heart_notes": ["Amber", "Rose", "Peony", "Geranium"], "base_notes": ["Vanilla", "Resin", "Musk", "Labdanum"],
     "scent_profile": {"Sweet": 90, "Warm": 85, "Floral": 60, "Woody": 40}, "best_season": "Autumn / Winter", "best_occasion": "Night Out & Sensual Dates", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W06", "name": "B&BW Gingham", "code": "W06", "gender": "Women", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Vibrant blue freesia, white peach, sweet clementine, and violet.",
     "top_notes": ["Blue Freesia", "Clementine"], "heart_notes": ["Violet", "White Peach"], "base_notes": ["Clean Musk", "Soft Blonde Woods"],
     "scent_profile": {"Fresh": 90, "Floral": 85, "Citrus": 70, "Sweet": 40}, "best_season": "Spring / Summer", "best_occasion": "Daily Routine & Sunny Days", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W07", "name": "B&BW Pink Chiffon", "code": "W07", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Sparkling red pear, peach blossom, wild berries, and spun sugar.",
     "top_notes": ["Wild Berries", "Pear", "Peach", "Mandarin"], "heart_notes": ["Apple Blossom", "Tiare Flower", "Jasmine", "Water Lily"], "base_notes": ["Vanilla", "Coconut", "Orchid", "Musk", "Heliotrope"],
     "scent_profile": {"Sweet": 95, "Floral": 70, "Fresh": 50, "Warm": 40}, "best_season": "Spring / Summer", "best_occasion": "Feminine Casual & Dates", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W08", "name": "B&BW Sweet Pea", "code": "W08", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Bright sweet pea, watery pear, sheer freesia, and luscious raspberry.",
     "top_notes": ["Sweet Pea", "Pear", "Tayberry", "Blackcurrant"], "heart_notes": ["Raspberry", "Freesia", "Pink Peony"], "base_notes": ["Plum Tree", "Musk"],
     "scent_profile": {"Floral": 90, "Sweet": 75, "Fresh": 70, "Citrus": 40}, "best_season": "Spring Days", "best_occasion": "Daytime & Casual Errands", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W09", "name": "B&BW Warm Vanilla Sugar", "code": "W09", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Cozy intoxicating blend of vanilla, white orchid, sparkling sugar, and sandalwood.",
     "top_notes": ["Vanilla", "Floral Notes"], "heart_notes": ["Rice", "Coconut", "Vanilla"], "base_notes": ["Sugar", "Vanilla", "Caramel", "Sandalwood", "Musk"],
     "scent_profile": {"Sweet": 95, "Warm": 90, "Woody": 40, "Fresh": 10}, "best_season": "Autumn / Winter", "best_occasion": "Cozy Evenings & Comfort Wear", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "W10", "name": "Be Delicious (DKNY)", "code": "W10", "gender": "Women", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Juicy American green apple, cucumber, grapefruit, and magnolia.",
     "top_notes": ["Cucumber", "Grapefruit", "Magnolia"], "heart_notes": ["Green Apple", "Lily-of-the-Valley", "Tuberose", "Violet", "Rose"], "base_notes": ["Woodsy Notes", "Sandalwood", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 80, "Floral": 60, "Sweet": 50}, "best_season": "Spring / Summer", "best_occasion": "City Walks & Daytime", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W11", "name": "Bench So In Love", "code": "W11", "gender": "Women", "category": "Floral", "tag": "Classic", "price": 250,
     "short_desc": "Beloved local romantic floral with soft rose, violet, and powder.",
     "top_notes": ["Citrus", "Apple"], "heart_notes": ["Rose", "Violet", "Jasmine"], "base_notes": ["Musk", "Powdery Accord"],
     "scent_profile": {"Floral": 85, "Fresh": 70, "Sweet": 50, "Warm": 30}, "best_season": "All Seasons", "best_occasion": "School, Daily & Romantic Hangs", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W12", "name": "Burberry Brit", "code": "W12", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Charming English blend of iced pear, sugary almond, and mahogany amber.",
     "top_notes": ["Almond", "Lime", "Pear"], "heart_notes": ["Candied Almond", "Sugar", "Peony"], "base_notes": ["Vanilla", "Tonka Bean", "Amber", "Mahogany"],
     "scent_profile": {"Sweet": 90, "Warm": 80, "Woody": 60, "Fresh": 30}, "best_season": "Autumn / Winter", "best_occasion": "Cozy Cafes & Autumn Walks", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W13", "name": "Burberry Weekend Women", "code": "W13", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Relaxed country floral of peach blossom, nectarine, wild rose, and iris.",
     "top_notes": ["Mignonette", "Mandarin Orange", "Sage"], "heart_notes": ["Nectarine", "Blue Hyacinth", "Peach Blossom", "Rose Hip", "Iris", "Red Cyclamen"], "base_notes": ["Musk", "Sandalwood", "Cedar"],
     "scent_profile": {"Floral": 90, "Fresh": 75, "Sweet": 60, "Woody": 40}, "best_season": "Spring / Summer", "best_occasion": "Weekend Brunches & Vacations", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W14", "name": "Can Can (Paris Hilton)", "code": "W14", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Playful cocktail of clementine, blackcurrant, wild orchid, and sweet amber.",
     "top_notes": ["Nectarine", "Blackcurrant", "Clementine"], "heart_notes": ["Wild Orchid", "Orange Blossom"], "base_notes": ["Amber", "Musk", "Woodsy Notes"],
     "scent_profile": {"Sweet": 90, "Floral": 60, "Citrus": 60, "Warm": 40}, "best_season": "Spring / Summer Nights", "best_occasion": "Parties & Fun Gatherings", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W15", "name": "Chanel Chance", "code": "W15", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Chic unpredictable floral with pink pepper, jasmine, and amber patchouli.",
     "top_notes": ["Patchouli", "Pink Pepper", "Pineapple", "Hyacinth", "Iris"], "heart_notes": ["Lemon", "Jasmine", "Rose"], "base_notes": ["Patchouli", "Musk", "Vetiver", "Vanilla"],
     "scent_profile": {"Floral": 85, "Woody": 70, "Fresh": 70, "Warm": 60}, "best_season": "All Seasons", "best_occasion": "Signature Elegance & Business", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "W16", "name": "Chanel No.5", "code": "W16", "gender": "Women", "category": "Floral", "tag": "Classic", "price": 250,
     "short_desc": "The eternal queen of perfumes: sparkling aldehydes, May rose, and sandalwood.",
     "top_notes": ["Aldehydes", "Ylang-Ylang", "Neroli", "Bergamot", "Lemon"], "heart_notes": ["Iris", "Jasmine", "Rose", "Orris Root", "Lily-of-the-Valley"], "base_notes": ["Civet", "Musk", "Sandalwood", "Amber", "Vanilla", "Oakmoss", "Patchouli"],
     "scent_profile": {"Floral": 90, "Warm": 85, "Woody": 70, "Fresh": 50}, "best_season": "Autumn / Winter / Evening", "best_occasion": "Gala, Black Tie & Timeless Events", "longevity": "10–12 hours", "projection": "Strong"},
    {"id": "W17", "name": "Clinique Happy Heart", "code": "W17", "gender": "Women", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Heartwarming wealth of white water lilies, mandarin, cucumber, and yellow primrose.",
     "top_notes": ["Cucumber", "Mandarin", "Cassia"], "heart_notes": ["Water Hyacinth", "Carrot"], "base_notes": ["White Woods", "Sandalwood"],
     "scent_profile": {"Fresh": 95, "Floral": 80, "Citrus": 60, "Woody": 30}, "best_season": "Spring Days", "best_occasion": "Daytime Office & Happy Occasions", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W18", "name": "Clinique Women", "code": "W18", "gender": "Women", "category": "Fresh", "tag": "Classic", "price": 250,
     "short_desc": "Bright sunny citrus with Hawaiian wedding flower and spring mimosa.",
     "top_notes": ["Orange", "Blood Grapefruit", "Indian Mandarin", "Bergamot", "Apple", "Plum"], "heart_notes": ["Lily-of-the-Valley", "Freesia", "Orchid", "Rose"], "base_notes": ["Mimosa", "Lily", "Magnolia", "Musk", "Amber"],
     "scent_profile": {"Citrus": 95, "Fresh": 90, "Floral": 70, "Sweet": 40}, "best_season": "Summer / Spring", "best_occasion": "Daylight Events & Casual", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W19", "name": "Coco Mademoiselle", "code": "W19", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Irresistible modern Parisian elegance: orange, Turkish rose, and patchouli.",
     "top_notes": ["Orange", "Mandarin", "Bergamot", "Orange Blossom"], "heart_notes": ["Turkish Rose", "Jasmine", "Mimosa", "Ylang-Ylang"], "base_notes": ["Patchouli", "White Musk", "Vanilla", "Vetiver", "Tonka Bean", "Opoponax"],
     "scent_profile": {"Floral": 85, "Woody": 80, "Citrus": 70, "Warm": 65}, "best_season": "All Seasons", "best_occasion": "Signature Luxury & Romantic Dinner", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "W20", "name": "Cool Water Women", "code": "W20", "gender": "Women", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Ocean breeze infused with lotus, water lily, melon, and quince.",
     "top_notes": ["Melon", "Lotus", "Lemon", "Pineapple", "Quince", "Calone", "Lily", "Blackcurrant"], "heart_notes": ["Lotus", "Water Lily", "Lily-of-the-Valley", "Jasmine", "Honey", "Hawthorn", "Rose"], "base_notes": ["Musk", "Vetiver", "Raspberry", "Blackberry", "Violet Root", "Peach", "Sandalwood", "Vanilla"],
     "scent_profile": {"Fresh": 95, "Floral": 75, "Sweet": 50, "Woody": 30}, "best_season": "Spring / Summer", "best_occasion": "Everyday Fresh & Beach Days", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W21", "name": "D&G Light Blue Women", "code": "W21", "gender": "Women", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Sicilian lemon, crisp Granny Smith apple, bluebells, and cedarwood.",
     "top_notes": ["Sicilian Lemon", "Apple", "Cedar", "Bellflower"], "heart_notes": ["Bamboo", "Jasmine", "White Rose"], "base_notes": ["Cedar", "Musk", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 90, "Woody": 60, "Floral": 50}, "best_season": "Summer Days", "best_occasion": "Vacations & Hot Tropical Days", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W22", "name": "Dior Poison", "code": "W22", "gender": "Women", "category": "Sweet", "tag": "Classic", "price": 250,
     "short_desc": "Dark bewitching potion of wild berries, honey, tuberose, and incense.",
     "top_notes": ["Plum", "Wild Berries", "Coriander", "Anise", "Brazilian Rosewood"], "heart_notes": ["Tuberose", "Incense", "White Honey", "Cinnamon", "Opoponax", "Carnation", "Jasmine", "African Orange Flower", "Rose"], "base_notes": ["Vanille", "Amber", "Sandalwood", "Heliotrope", "Musk", "Vetiver", "Virginia Cedar"],
     "scent_profile": {"Warm": 95, "Sweet": 90, "Floral": 70, "Woody": 60}, "best_season": "Winter / Night", "best_occasion": "Special Glamour & Seductive Evening", "longevity": "12+ hours", "projection": "Enormous"},
    {"id": "W23", "name": "Eclat d'Arpege (Lanvin)", "code": "W23", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Delicate harmony of green lilac, peach blossom, wisteria, and tea leaves.",
     "top_notes": ["Green Lilac", "Tea Leaf"], "heart_notes": ["Peach Blossom", "Peony", "Wisteria", "Osmanthus", "Petitgrain"], "base_notes": ["Musk", "Cedar", "Amber"],
     "scent_profile": {"Floral": 90, "Fresh": 85, "Sweet": 40, "Woody": 30}, "best_season": "Spring Days", "best_occasion": "Romantic Brunches & Daily Soft Fragrance", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W24", "name": "Elizabeth Arden Green Tea", "code": "W24", "gender": "Women", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Energizing revitalizing mist of green tea, rhubarb, mint, and lemon zest.",
     "top_notes": ["Lemon", "Bergamot", "Mint", "Orange Peel", "Rhubarb"], "heart_notes": ["Jasmine", "Oakmoss", "Fennel", "Musk", "Carnation", "White Amber"], "base_notes": ["Green Tea", "Jasmine", "Oakmoss", "Musk", "Celery Seeds", "Caraway", "Cloves", "Amber"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Floral": 40, "Warm": 20}, "best_season": "Spring / Summer", "best_occasion": "Office, Post-Workout & Daily Comfort", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W25", "name": "Fantasy (Britney Spears)", "code": "W25", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Sweet magic love potion of red lychee, kiwi, white chocolate cupcake, and orchid.",
     "top_notes": ["Kiwi", "Red Litchi", "Quince"], "heart_notes": ["White Chocolate", "Cupcake", "Orchid", "Jasmine"], "base_notes": ["Musk", "Woodsy Notes", "Orris Root"],
     "scent_profile": {"Sweet": 98, "Warm": 80, "Fresh": 40, "Floral": 40}, "best_season": "Autumn / Winter", "best_occasion": "Date Night & Playful Days", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "W26", "name": "Good Girl (Carolina Herrera)", "code": "W26", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Audacious mix of white tuberose, roasted tonka bean, and dark cacao.",
     "top_notes": ["Almond", "Coffee", "Bergamot", "Lemon"], "heart_notes": ["Tuberose", "Jasmine Sambac", "Orange Blossom", "Orris", "Bulgarian Rose"], "base_notes": ["Tonka Bean", "Cacao", "Vanilla", "Praline", "Sandalwood", "Musk", "Amber", "Cashmere Wood", "Cinnamon", "Patchouli", "Cedar"],
     "scent_profile": {"Sweet": 90, "Warm": 90, "Floral": 75, "Woody": 60}, "best_season": "Autumn / Winter", "best_occasion": "High Heels, Parties & Evening Seduction", "longevity": "10–12 hours", "projection": "Strong"},
    {"id": "W27", "name": "Gucci Rush", "code": "W27", "gender": "Women", "category": "Floral", "tag": "Classic", "price": 250,
     "short_desc": "Addictive retro cocktail of California gardenia, peach, coriander, and patchouli.",
     "top_notes": ["Peach", "California Gardenia", "African Freesia Petals"], "heart_notes": ["Coriander", "Damask Rose", "Jasmine"], "base_notes": ["Patchouli", "Natural Vanilla", "Vetiver"],
     "scent_profile": {"Floral": 85, "Warm": 85, "Woody": 70, "Sweet": 60}, "best_season": "Autumn / Winter", "best_occasion": "Night Out & Bold Clubbing", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "W28", "name": "Guess Women", "code": "W28", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Feminine juicy green apple, strawberry, peony, magnolia, and amber musk.",
     "top_notes": ["Green Apple", "Strawberry", "Bergamot", "Tangerine"], "heart_notes": ["Peony", "Magnolia", "Freesia", "Peach", "Jasmine", "Ylang-Ylang", "Lily-of-the-Valley", "Red Berries"], "base_notes": ["Amber", "Musk", "Oakmoss", "Cedar"],
     "scent_profile": {"Floral": 85, "Sweet": 75, "Fresh": 70, "Woody": 40}, "best_season": "Spring / Summer", "best_occasion": "Casual Daily Wear", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W29", "name": "Heiress (Paris Hilton)", "code": "W29", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Bubbly champagne mimosa, passionfruit, peach granita, and star jasmine.",
     "top_notes": ["Passionfruit", "Peach", "Champagne", "Mimosa", "Orange"], "heart_notes": ["Honeysuckle", "Star Jasmine", "Ylang-Ylang", "Tiare Flower", "Grenadine"], "base_notes": ["Tonka Bean", "White Woods", "Violet Leaf"],
     "scent_profile": {"Sweet": 90, "Fresh": 75, "Floral": 60, "Citrus": 50}, "best_season": "Spring / Summer", "best_occasion": "Celebrations & Parties", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W30", "name": "Incanto Charm", "code": "W30", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Magical fruity bouquet of sweet passionfruit, honeysuckle, and rose.",
     "top_notes": ["Passionfruit", "Honeysuckle"], "heart_notes": ["Rose", "Jasmine"], "base_notes": ["White Musk", "Woodsy Notes"],
     "scent_profile": {"Floral": 85, "Sweet": 80, "Fresh": 70, "Woody": 30}, "best_season": "Spring / Summer", "best_occasion": "Day Trips & Casual Fun", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W31", "name": "Incanto Shine", "code": "W31", "gender": "Women", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Tropical sunshine packed with juicy pineapple, passionfruit, and freesia.",
     "top_notes": ["Pineapple", "Passionfruit", "Bergamot"], "heart_notes": ["Peach", "Pink Peony", "Freesia"], "base_notes": ["Musk", "Cedar", "Amber"],
     "scent_profile": {"Fresh": 90, "Sweet": 80, "Citrus": 75, "Floral": 60}, "best_season": "Summer Days", "best_occasion": "Sunny Outings & Vacation", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W32", "name": "Jean Paul Classique", "code": "W32", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Warm seductive orange blossom, ginger, rose, and comforting amber vanilla.",
     "top_notes": ["Orange Blossom", "Star Anise", "Rose", "Mandarin", "Pear", "Bergamot"], "heart_notes": ["Ylang-Ylang", "Ginger", "Orchid", "Iris", "Tuberose", "Plum"], "base_notes": ["Vanilla", "Amber", "Musk", "Cinnamon", "Sandalwood"],
     "scent_profile": {"Floral": 90, "Warm": 90, "Sweet": 80, "Woody": 50}, "best_season": "Autumn / Winter", "best_occasion": "Formal Evening & Romance", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "W33", "name": "Jo Malone English Pear", "code": "W33", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Orchard freshness of just-ripe King William pears wrapped in white freesias.",
     "top_notes": ["Pear", "Melon"], "heart_notes": ["Freesia", "Rose"], "base_notes": ["Musk", "Patchouli", "Rhubarb", "Amber"],
     "scent_profile": {"Floral": 90, "Fresh": 85, "Sweet": 50, "Woody": 40}, "best_season": "Spring / Autumn", "best_occasion": "Daytime Brunches & Daily Elegance", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W34", "name": "Jo Malone Nectarine Blossom", "code": "W34", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Juicy succulent nectarine, peach, and cassis laced with acacia honey.",
     "top_notes": ["Green Notes", "Blackcurrant", "Petitgrain"], "heart_notes": ["Nectarine", "Black Locust"], "base_notes": ["Peach", "Plum", "Vetiver"],
     "scent_profile": {"Sweet": 85, "Fresh": 80, "Citrus": 60, "Floral": 50}, "best_season": "Spring / Summer", "best_occasion": "Garden Parties & Afternoon Tea", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W35", "name": "Jo Malone Peony & Blush Suede", "code": "W35", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Voluptuous blooming peonies, juicy red apple, and sensual soft suede.",
     "top_notes": ["Red Apple"], "heart_notes": ["Peony", "Rose", "Jasmine", "Carnation"], "base_notes": ["Suede"],
     "scent_profile": {"Floral": 95, "Sweet": 60, "Fresh": 60, "Warm": 50}, "best_season": "Spring Days", "best_occasion": "Weddings, High Tea & Dates", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W36", "name": "Jo Malone Sakura Cherry Blossom", "code": "W36", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Ethereal Japanese cherry blossom petals, rose, and sparkling bergamot.",
     "top_notes": ["Bergamot", "Mandarin Orange"], "heart_notes": ["Cherry Blossom", "Rose", "Mimosa"], "base_notes": ["Musk", "Woody Notes"],
     "scent_profile": {"Floral": 95, "Fresh": 80, "Citrus": 50, "Sweet": 40}, "best_season": "Springtime", "best_occasion": "Romantic Day Out & Casual", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W37", "name": "Jovan Musk", "code": "W37", "gender": "Women", "category": "Floral", "tag": "Classic", "price": 250,
     "short_desc": "Vintage sexy musk blended with jasmine, neroli, and bergamot.",
     "top_notes": ["Star Anise", "Bergamot", "Peach"], "heart_notes": ["Ylang-Ylang", "Lavender", "Butter"], "base_notes": ["Musk", "Patchouli", "Vetiver"],
     "scent_profile": {"Warm": 85, "Floral": 75, "Woody": 60, "Sweet": 40}, "best_season": "All Seasons", "best_occasion": "Comfortable Daily & Intimate", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W38", "name": "Just a Kiss (Victoria's Secret)", "code": "W38", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Glossy sweet lip tint vibe with peony petals and iced pink pepper.",
     "top_notes": ["Pink Pepper"], "heart_notes": ["Peony"], "base_notes": ["Lip Gloss Accord"],
     "scent_profile": {"Floral": 85, "Sweet": 80, "Fresh": 70, "Warm": 30}, "best_season": "Spring / Summer", "best_occasion": "Dating & Playful Days", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W39", "name": "Katy Perry Purr", "code": "W39", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Sweet peach nectar, apple, bamboo, jasmine, and vanilla orchid.",
     "top_notes": ["Peach", "Apple", "Gardenia", "Bamboo"], "heart_notes": ["Jasmine", "Freesia", "Rose"], "base_notes": ["Vanilla", "Coconut", "Amber", "Musk", "Sandalwood"],
     "scent_profile": {"Sweet": 90, "Floral": 70, "Fresh": 60, "Warm": 50}, "best_season": "Spring / Autumn", "best_occasion": "Casual & Fun Gatherings", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W40", "name": "Killer Queen (Katy Perry)", "code": "W40", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Royal dark berries, red velvet flower, patchouli, and liquid praline.",
     "top_notes": ["Forest Fruit", "Plum", "Bergamot"], "heart_notes": ["Frangipani", "Jasmine Sambac", "Celosia"], "base_notes": ["Praline", "Patchouli", "Cashmeran"],
     "scent_profile": {"Sweet": 90, "Warm": 85, "Woody": 60, "Floral": 50}, "best_season": "Autumn / Winter", "best_occasion": "Evening Out & Statement Scent", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W41", "name": "Lacoste Touch of Pink", "code": "W41", "gender": "Women", "category": "Fresh", "tag": "Best Seller", "price": 250,
     "short_desc": "Energetic blood orange, coriander, cardamom, violet, and soft vanilla.",
     "top_notes": ["Orange", "Peach", "Blood Orange", "Coriander", "Cardamom"], "heart_notes": ["Jasmine", "Coriander", "Cardamom", "Violet Leaf", "Carrot Seeds"], "base_notes": ["Vanilla", "Musk", "Sandalwood"],
     "scent_profile": {"Fresh": 90, "Citrus": 85, "Sweet": 65, "Floral": 50}, "best_season": "Spring / Summer", "best_occasion": "Campus, Sports & Daily Wear", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W42", "name": "Meow by Katy Perry", "code": "W42", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Sweet candy shop of pear, tangerine, vanilla, gardenia, and amber.",
     "top_notes": ["Tangerine", "Pear", "Gardenia", "Jasmine"], "heart_notes": ["Honeysuckle", "African Orange Flower", "Lily-of-the-Valley"], "base_notes": ["Vanilla", "Amber", "Musk", "Sandalwood"],
     "scent_profile": {"Sweet": 95, "Floral": 60, "Warm": 60, "Citrus": 40}, "best_season": "Autumn / Winter / Spring", "best_occasion": "Cute Dates & Everyday Sweetness", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W43", "name": "Miss Dior", "code": "W43", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Millefiori floral bouquet of Grasse rose, iris, peony, and tender woods.",
     "top_notes": ["Iris", "Peony", "Lily-of-the-Valley"], "heart_notes": ["Apricot", "Rose", "Peach"], "base_notes": ["Vanilla", "Musk", "Tonka Bean", "Benzoin", "Sandalwood"],
     "scent_profile": {"Floral": 95, "Sweet": 65, "Fresh": 60, "Warm": 50}, "best_season": "Spring / Autumn", "best_occasion": "Weddings, Dates & Elegant Dinners", "longevity": "8–10 hours", "projection": "Strong"},
    {"id": "W44", "name": "Moon Sparkle (Escada)", "code": "W44", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Nightclub berries, strawberry, blackcurrant, red apple, and sweet amber.",
     "top_notes": ["Strawberry", "Blackcurrant", "Red Apple", "Citrus"], "heart_notes": ["Sweet Pea", "Freesia", "Jasmine", "Rose"], "base_notes": ["Raspberry", "Musk", "Sandalwood", "Amber"],
     "scent_profile": {"Sweet": 95, "Fresh": 75, "Floral": 60, "Warm": 40}, "best_season": "Summer Nights", "best_occasion": "Parties & Evening Fun", "longevity": "6–8 hours", "projection": "Moderate to Strong"},
    {"id": "W45", "name": "Narciso Rodriguez For Her", "code": "W45", "gender": "Women", "category": "Floral", "tag": "Classic", "price": 250,
     "short_desc": "Sensual musky heart enhanced by pink floral osmanthus and soft amber.",
     "top_notes": ["African Orange Flower", "Osmanthus", "Bergamot"], "heart_notes": ["Musk", "Amber"], "base_notes": ["Vetiver", "Vanille", "Patchouli"],
     "scent_profile": {"Warm": 90, "Floral": 80, "Woody": 70, "Fresh": 40}, "best_season": "Autumn / Winter", "best_occasion": "Intimate Dates & Luxury Events", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "W46", "name": "Omnia Amethyste", "code": "W46", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Noble iris, Bulgarian rosebuds, pink grapefruit, and heliotrope.",
     "top_notes": ["Pink Grapefruit", "Green Notes"], "heart_notes": ["Iris", "Bulgarian Rose"], "base_notes": ["Heliotrope", "Woodsy Notes"],
     "scent_profile": {"Floral": 90, "Fresh": 80, "Citrus": 50, "Woody": 40}, "best_season": "Spring Days", "best_occasion": "Office & Gentle Daytime Wear", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W47", "name": "Paris Hilton", "code": "W47", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Flirtatious frozen apple, peach nectar, freesia, and shimmering jasmine.",
     "top_notes": ["Melon", "Apple", "Peach"], "heart_notes": ["Freesia", "Mimosa", "Jasmine", "Lily-of-the-Valley", "Tuberose"], "base_notes": ["Musk", "Ylang-Ylang", "Oakmoss", "Sandalwood"],
     "scent_profile": {"Sweet": 90, "Fresh": 80, "Floral": 70, "Woody": 30}, "best_season": "Spring / Summer", "best_occasion": "Social Gatherings & Parties", "longevity": "6–8 hours", "projection": "Moderate to Strong"},
    {"id": "W48", "name": "Prada Candy", "code": "W48", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Pure indulgence of golden caramel, warm powdery musk, and rich benzoin.",
     "top_notes": ["Caramel"], "heart_notes": ["Powdery Notes", "Musk"], "base_notes": ["Benzoin", "Vanilla"],
     "scent_profile": {"Sweet": 98, "Warm": 90, "Woody": 30, "Fresh": 10}, "best_season": "Autumn / Winter", "best_occasion": "Cozy Dates & Evening Dinners", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W49", "name": "Santal 33 (Le Labo)", "code": "W49", "gender": "Unisex", "category": "Woody", "tag": "Best Seller", "price": 250,
     "short_desc": "Smoky Australian sandalwood, cardamom, violet, iris, and leather.",
     "top_notes": ["Cardamom", "Violet Accord"], "heart_notes": ["Iris", "Papyrus", "Ambrox"], "base_notes": ["Cedarwood", "Leather", "Sandalwood"],
     "scent_profile": {"Woody": 98, "Warm": 85, "Fresh": 40, "Sweet": 20}, "best_season": "All Seasons", "best_occasion": "Artistic Signature & Urban Chic", "longevity": "12+ hours", "projection": "Strong"},
    {"id": "W50", "name": "Scandal (Jean Paul Gaultier)", "code": "W50", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Delicious dripping gourmet honey, gardenia, blood orange, and patchouli.",
     "top_notes": ["Blood Orange", "Mandarin Orange"], "heart_notes": ["Honey", "Gardenia", "Orange Blossom", "Jasmine", "Peach"], "base_notes": ["Beeswax", "Caramel", "Patchouli", "Licorice"],
     "scent_profile": {"Sweet": 98, "Warm": 90, "Floral": 65, "Citrus": 40}, "best_season": "Autumn / Winter", "best_occasion": "Night Out & Seduction", "longevity": "10–12 hours", "projection": "Enormous"},
    {"id": "W51", "name": "Selena Gomez", "code": "W51", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Raspberry, peach, chocolate, vanilla, and sweet pineapple harmony.",
     "top_notes": ["Raspberry", "Peach", "Pineapple", "Orange"], "heart_notes": ["Blackberry", "Freesia", "Musk"], "base_notes": ["Dark Chocolate", "Vanilla", "Coconut", "Amber"],
     "scent_profile": {"Sweet": 95, "Fresh": 65, "Warm": 60, "Floral": 40}, "best_season": "Spring / Autumn", "best_occasion": "Casual Fun & Daytime Outings", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W52", "name": "Sweet Like Candy (Ariana)", "code": "W52", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Sugar-frosted blackberries, fluffy marshmallow, and creamy vanilla.",
     "top_notes": ["Blackberry", "Pear", "Bergamot"], "heart_notes": ["Whipped Cream", "Marshmallow", "Blackcurrant", "Frangipani", "Jasmine", "Honeysuckle"], "base_notes": ["Vanilla", "Cashmere Wood"],
     "scent_profile": {"Sweet": 99, "Floral": 50, "Warm": 50, "Fresh": 30}, "best_season": "All Seasons", "best_occasion": "Sweet Daytime & Youthful Hangouts", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W53", "name": "Tommy Girl", "code": "W53", "gender": "Women", "category": "Fresh", "tag": "Popular", "price": 250,
     "short_desc": "Refreshing spearmint, blackcurrant, camellia flower, and apple blossom.",
     "top_notes": ["Apple Tree Blossom", "Camellia", "Mandarin", "Blackcurrant"], "heart_notes": ["Lemon", "Honeysuckle", "Rose", "Grapefruit", "Lily", "Mint", "Violet"], "base_notes": ["Magnolia", "Jasmine", "Cedar", "Sandalwood", "Leather"],
     "scent_profile": {"Fresh": 95, "Citrus": 85, "Floral": 75, "Sweet": 40}, "best_season": "Spring / Summer", "best_occasion": "Campus, Sports & Daily Routine", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W54", "name": "Valaya (Parfums de Marly)", "code": "W54", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Pure white silk: radiant aldehydes, orange blossom, white peach, and akigalawood.",
     "top_notes": ["Aldehydes", "White Peach", "Bergamot", "Mandarin Orange"], "heart_notes": ["Orange Blossom", "Petalia", "Lily-of-the-Valley", "Vetiver", "Mahonia"], "base_notes": ["Musk", "Ambroxan", "Akigalawood", "Vanilla"],
     "scent_profile": {"Floral": 90, "Fresh": 90, "Woody": 70, "Warm": 50}, "best_season": "All Seasons", "best_occasion": "Haute Luxury, Weddings & Everyday Chic", "longevity": "10–12 hours", "projection": "Strong"},
    {"id": "W55", "name": "Versace Bright Crystal", "code": "W55", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Luminous pomegranate seeds, chilled yuzu, peony petals, and magnolia.",
     "top_notes": ["Yuzu", "Pomegranate", "Ice"], "heart_notes": ["Peony", "Lotus", "Magnolia"], "base_notes": ["Musk", "Mahogany", "Amber"],
     "scent_profile": {"Floral": 90, "Fresh": 90, "Citrus": 70, "Sweet": 45}, "best_season": "Spring / Summer", "best_occasion": "Everyday Elegance & Office", "longevity": "7–9 hours", "projection": "Moderate"},
    {"id": "W56", "name": "VS Amber Romance", "code": "W56", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Warm sensual amber, creamy crème anglaise, and comforting vanilla.",
     "top_notes": ["Black Cherry"], "heart_notes": ["Crème Anglaise", "Chamomile"], "base_notes": ["Amber", "Vanilla", "Sandalwood"],
     "scent_profile": {"Sweet": 90, "Warm": 95, "Woody": 45, "Fresh": 10}, "best_season": "Autumn / Winter", "best_occasion": "Cozy Evenings & Intimate Wear", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W57", "name": "VS Bare Vanilla", "code": "W57", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Whipped vanilla cream and soft apple blossom wrapped in cashmere.",
     "top_notes": ["Whipped Vanilla"], "heart_notes": ["Soft Apple Blossom"], "base_notes": ["Cashmeran"],
     "scent_profile": {"Sweet": 98, "Warm": 85, "Woody": 30, "Fresh": 15}, "best_season": "All Seasons", "best_occasion": "Daily Comfort & Bedtime Cozy", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W58", "name": "VS Bombshell", "code": "W58", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "America's favorite purple passion fruit, Shangri-la peony, and vanilla orchid.",
     "top_notes": ["Passionfruit", "Grapefruit", "Pineapple", "Tangerine", "Big Strawberry"], "heart_notes": ["Peony", "Vanilla Orchid", "Red Berries", "Jasmine", "Lily-of-the-Valley"], "base_notes": ["Musk", "Woody Notes", "Oakmoss"],
     "scent_profile": {"Floral": 90, "Sweet": 80, "Fresh": 80, "Citrus": 60}, "best_season": "Spring / Summer", "best_occasion": "Confidence Boost & All-Day Casual", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W59", "name": "VS Choco Vanilla", "code": "W59", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Decadent melted milk chocolate and rich vanilla frosting.",
     "top_notes": ["Cacao Pod", "Sugar"], "heart_notes": ["Milk Chocolate", "Vanilla Flower"], "base_notes": ["Bourbon Vanilla", "Amber"],
     "scent_profile": {"Sweet": 99, "Warm": 90, "Woody": 20, "Fresh": 10}, "best_season": "Autumn / Winter", "best_occasion": "Sweet Comfort & Dessert Nights", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W60", "name": "VS Endless Love", "code": "W60", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Enchanting apple blossom, peach, pomegranate, and tender ylang-ylang.",
     "top_notes": ["Apple Blossom", "Peach"], "heart_notes": ["Pomegranate", "Ylang-Ylang"], "base_notes": ["Musk", "Woody Notes"],
     "scent_profile": {"Floral": 85, "Sweet": 80, "Fresh": 75, "Citrus": 40}, "best_season": "Spring Days", "best_occasion": "Casual & Sweet Day Out", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W61", "name": "VS Love Spell", "code": "W61", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Hypnotic blend of cherry blossom, fresh peach, and white jasmine.",
     "top_notes": ["Peach", "Cherry Blossom", "Red Apple"], "heart_notes": ["Lilac", "Jasmine", "Lily-of-the-Valley"], "base_notes": ["Tamarind", "Musk", "White Woods"],
     "scent_profile": {"Sweet": 90, "Floral": 80, "Fresh": 75, "Citrus": 50}, "best_season": "Spring / Summer", "best_occasion": "School, Dates & Everyday Fun", "longevity": "6–8 hours", "projection": "Moderate to Strong"},
    {"id": "W62", "name": "VS Pure Seduction", "code": "W62", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Juicy red plum, crushed freesia, and sweet melon confection.",
     "top_notes": ["Plum", "Melon"], "heart_notes": ["Freesia", "Floral Notes"], "base_notes": ["Chamomile", "Musk"],
     "scent_profile": {"Sweet": 95, "Floral": 75, "Fresh": 65, "Warm": 40}, "best_season": "All Seasons", "best_occasion": "Flirty Hangouts & Casual", "longevity": "6–8 hours", "projection": "Moderate to Strong"},
    {"id": "W63", "name": "VS Romantic Wish", "code": "W63", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Romantic pink peony, sparkling pomegranate, and sheer freesia.",
     "top_notes": ["Pomegranate"], "heart_notes": ["Peony", "Freesia"], "base_notes": ["Musk"],
     "scent_profile": {"Floral": 85, "Sweet": 75, "Fresh": 70, "Warm": 30}, "best_season": "Spring / Summer", "best_occasion": "Sweet Romance & Daylight", "longevity": "5–7 hours", "projection": "Moderate"},
    {"id": "W64", "name": "VS Scandalous", "code": "W64", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Provocative raspberry liqueur, black peony, and sweet praline.",
     "top_notes": ["Raspberry Liqueur"], "heart_notes": ["Black Peony"], "base_notes": ["Praline"],
     "scent_profile": {"Sweet": 92, "Floral": 70, "Warm": 70, "Fresh": 30}, "best_season": "Autumn / Winter", "best_occasion": "Evening Seduction & Party", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W65", "name": "VS Sexy Little Things", "code": "W65", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Sensual water lily, apple, osmanthus, and shimmering amber.",
     "top_notes": ["Apple", "Water Lily", "Osmanthus"], "heart_notes": ["Jasmine", "Lotus", "Honeysuckle"], "base_notes": ["Musk", "Cashmere Wood", "Amber"],
     "scent_profile": {"Floral": 85, "Fresh": 80, "Sweet": 65, "Woody": 40}, "best_season": "Spring / Summer", "best_occasion": "Dating & Nights Out", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W66", "name": "VS Strawberry & Champagne", "code": "W66", "gender": "Women", "category": "Sweet", "tag": "Classic", "price": 250,
     "short_desc": "Bubbly champagne, sweet wild strawberries, cassis, and white peach.",
     "top_notes": ["Wild Strawberry", "Champagne"], "heart_notes": ["Cassis", "White Peach"], "base_notes": ["Musk", "Sandalwood"],
     "scent_profile": {"Sweet": 90, "Fresh": 80, "Citrus": 60, "Floral": 40}, "best_season": "Spring / Summer", "best_occasion": "Party, Brunch & Celebration", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W67", "name": "VS Vanilla Lace", "code": "W67", "gender": "Women", "category": "Sweet", "tag": "Best Seller", "price": 250,
     "short_desc": "Pure nostalgic vanilla orchid, warm musk, and sweet amber sugar.",
     "top_notes": ["Vanilla"], "heart_notes": ["Vanilla Orchid"], "base_notes": ["Musk", "Amber"],
     "scent_profile": {"Sweet": 98, "Warm": 90, "Woody": 30, "Fresh": 10}, "best_season": "Autumn / Winter", "best_occasion": "Daily Sweet Signature & Bedtime", "longevity": "7–9 hours", "projection": "Moderate to Strong"},
    {"id": "W68", "name": "VS Velvet Petals", "code": "W68", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Lush floral blooms and sweet almond glaze with cozy undertones.",
     "top_notes": ["Sweet Almond Glaze"], "heart_notes": ["Lush Blooms", "Starfruit"], "base_notes": ["Sandalwood", "Praline"],
     "scent_profile": {"Floral": 85, "Sweet": 85, "Warm": 65, "Fresh": 40}, "best_season": "Spring / Autumn", "best_occasion": "Casual & Flirty Wear", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W69", "name": "VS Wild Scarlet", "code": "W69", "gender": "Women", "category": "Floral", "tag": "Popular", "price": 250,
     "short_desc": "Juicy apple, crimson lily, and luminous amber flower bouquet.",
     "top_notes": ["Juicy Apple"], "heart_notes": ["Crimson Lily"], "base_notes": ["Amber"],
     "scent_profile": {"Floral": 85, "Sweet": 75, "Fresh": 70, "Warm": 40}, "best_season": "Spring / Summer", "best_occasion": "Daytime Energy & Dates", "longevity": "6–8 hours", "projection": "Moderate"},
    {"id": "W70", "name": "YSL Black Opium", "code": "W70", "gender": "Women", "category": "Sweet", "tag": "Popular", "price": 250,
     "short_desc": "Addictive black coffee, white florals, bitter almond, and sweet vanilla.",
     "top_notes": ["Pear", "Pink Pepper", "Orange Blossom"], "heart_notes": ["Coffee", "Jasmine", "Bitter Almond", "Licorice"], "base_notes": ["Vanilla", "Patchouli", "Cashmere Wood", "Cedar"],
     "scent_profile": {"Sweet": 92, "Warm": 90, "Floral": 60, "Fresh": 20}, "best_season": "Autumn / Winter", "best_occasion": "Night Out & Sensual Evening", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "W71", "name": "YSL Libre", "code": "W71", "gender": "Women", "category": "Floral", "tag": "Best Seller", "price": 250,
     "short_desc": "Grand floral lavender from France, Moroccan orange blossom, and Madagascar vanilla.",
     "top_notes": ["Lavender", "Mandarin Orange", "Blackcurrant", "Petitgrain"], "heart_notes": ["Lavender", "Orange Blossom", "Jasmine"], "base_notes": ["Madagascar Vanilla", "Musk", "Cedar", "Ambergris"],
     "scent_profile": {"Floral": 90, "Fresh": 75, "Warm": 75, "Sweet": 60}, "best_season": "All Seasons", "best_occasion": "Boss Lady Office & Evening Events", "longevity": "9–11 hours", "projection": "Strong"},
    {"id": "W72", "name": "360 Perry Ellis Purple", "code": "W72", "gender": "Women", "category": "Floral", "tag": "Classic", "price": 250,
     "short_desc": "Wild blackberry, apple blossom, pink rose, and purple mimosa.",
     "top_notes": ["Blackberry", "Apple Blossom", "Peach"], "heart_notes": ["Pink Rose", "Lily-of-the-Valley", "Mimosa", "Tuberose", "Jasmine"], "base_notes": ["Musk", "Oakmoss", "Sandalwood"],
     "scent_profile": {"Floral": 90, "Sweet": 70, "Fresh": 70, "Woody": 40}, "best_season": "Spring / Summer", "best_occasion": "Everyday Office & Casual Outing", "longevity": "6–8 hours", "projection": "Moderate"}
]

@app.get("/")
def root():
    return {
        "brand": "AURUM PARFUM",
        "tagline": "Wear Confidence",
        "bottle_size": "60ml / 1.7 fl. oz. Eau De Parfum",
        "pricing": "₱250 each | Buy 2 for ₱450 (Save ₱50)",
        "total_fragrances": len(perfumes),
        "docs": "/docs"
    }

@app.get("/perfumes")
def get_perfumes(
    category: Optional[str] = None,
    gender: Optional[str] = None,
    tag: Optional[str] = None
):
    results = perfumes
    if category and category.lower() != "all":
        results = [p for p in results if p["category"].lower() == category.lower()]
    if gender and gender.lower() != "all":
        results = [p for p in results if p["gender"].lower() == gender.lower()]
    if tag and tag.lower() != "all":
        results = [p for p in results if p["tag"].lower() == tag.lower()]
    return results

@app.get("/perfumes/search")
def search_perfumes(q: str = ""):
    query = q.lower().strip()
    if not query:
        return perfumes
    
    results = []
    for p in perfumes:
        searchable_text = f"{p['name']} {p['code']} {p['category']} {p['gender']} {p['short_desc']} {' '.join(p['top_notes'])} {' '.join(p['heart_notes'])} {' '.join(p['base_notes'])}".lower()
        if query in searchable_text:
            results.append(p)
    return results

@app.get("/perfumes/{perfume_id}")
def get_perfume_detail(perfume_id: str):
    for p in perfumes:
        if str(p["id"]).lower() == str(perfume_id).lower() or str(p["code"]).lower() == str(perfume_id).lower():
            return p
    raise HTTPException(status_code=404, detail="Perfume not found in Aurum catalog")